# Generated by Django 4.0.6 on 2022-07-13 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=128, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('university', models.CharField(max_length=128, verbose_name='Образование')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('comment', models.TextField(blank=True, max_length=512, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Пользователь активен?')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
